export const CURRENCY_DETAILS_REQUEST = 'CURRENCY_DETAILS_REQUEST';
export const CURRENCY_DETAILS_SUCCESS = 'CURRENCY_DETAILS_SUCCESS';
export const CURRENCY_DETAILS_FAIL = 'CURRENCY_DETAILS_FAIL';

export const CURRENCY_VALUE_REQUEST = 'CURRENCY_VALUE_REQUEST';
export const CURRENCY_VALUE_SUCCESS = 'CURRENCY_VALUE_SUCCESS';
export const CURRENCY_VALUE_FAIL = 'CURRENCY_VALUE_FAIL';
